import { UserRole } from '@prisma/client';

export enum Permission {
  MANAGE_TENANTS = 'MANAGE_TENANTS',
  MANAGE_USERS = 'MANAGE_USERS',
  CUSTOMER_CRUD = 'CUSTOMER_CRUD',
  CUSTOMER_VIEW = 'CUSTOMER_VIEW',
  DRIVER_CRUD = 'DRIVER_CRUD',
  DRIVER_VIEW = 'DRIVER_VIEW',
  VEHICLE_CRUD = 'VEHICLE_CRUD',
  VEHICLE_VIEW = 'VEHICLE_VIEW',
  CREATE_BOOKING = 'CREATE_BOOKING',
  ASSIGN_RESOURCES = 'ASSIGN_RESOURCES',
  GENERATE_DUTY_SLIP = 'GENERATE_DUTY_SLIP',
  CLOSE_TRIP = 'CLOSE_TRIP',
  INVOICE_CRUD = 'INVOICE_CRUD',
  RECORD_PAYMENT = 'RECORD_PAYMENT',
  FINANCIAL_REPORTS = 'FINANCIAL_REPORTS',
  OPERATIONS_REPORTS = 'OPERATIONS_REPORTS',
  RATE_CRUD = 'RATE_CRUD',
  RATE_VIEW = 'RATE_VIEW',
}

export const RolePermissions: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: Object.values(Permission),
  OPERATOR_ADMIN: [
    Permission.MANAGE_USERS,
    Permission.CUSTOMER_CRUD,
    Permission.CUSTOMER_VIEW,
    Permission.DRIVER_CRUD,
    Permission.DRIVER_VIEW,
    Permission.VEHICLE_CRUD,
    Permission.VEHICLE_VIEW,
    Permission.CREATE_BOOKING,
    Permission.ASSIGN_RESOURCES,
    Permission.GENERATE_DUTY_SLIP,
    Permission.CLOSE_TRIP,
    Permission.INVOICE_CRUD,
    Permission.RECORD_PAYMENT,
    Permission.FINANCIAL_REPORTS,
    Permission.OPERATIONS_REPORTS,
    Permission.RATE_CRUD,
    Permission.RATE_VIEW,
  ],
  DISPATCHER: [
    Permission.CUSTOMER_VIEW,
    Permission.DRIVER_CRUD,
    Permission.DRIVER_VIEW,
    Permission.VEHICLE_CRUD,
    Permission.VEHICLE_VIEW,
    Permission.CREATE_BOOKING,
    Permission.ASSIGN_RESOURCES,
    Permission.GENERATE_DUTY_SLIP,
    Permission.CLOSE_TRIP,
    Permission.OPERATIONS_REPORTS,
    Permission.RATE_VIEW,
  ],
  BILLING_EXECUTIVE: [
    Permission.CUSTOMER_VIEW,
    Permission.DRIVER_VIEW,
    Permission.VEHICLE_VIEW,
    Permission.CLOSE_TRIP,
    Permission.INVOICE_CRUD,
    Permission.RECORD_PAYMENT,
    Permission.FINANCIAL_REPORTS,
    Permission.RATE_VIEW,
  ],
};
